server:
  port: 8080
  servlet:
    context-path: /graduate

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://172.20.0.2:3306/levelSchool
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      validation-query: select 1
#    filters=stat
#    initialSize=2
#    maxActive=300
#    maxWait=60000
#    timeBetweenEvictionRunsMillis=60000
#    minEvictableIdleTimeMillis=300000
#    validationQuery=SELECT 1
#    testWhileIdle=true
#    testOnBorrow=false
#    testOnReturn=false
#    poolPreparedStatements=false
#    maxPoolPreparedStatementPerConnectionSize=200

  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
    timeout: 10000


mybatis-plus:
  type-aliases-package: com.txy.graduate.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

markerhub:
  jwt:
    secret: hfjshgohirehigtiuuoighrehuir13fe
    header: Authorization
    expireTime: 604800 #7t天
