# 生产环境
spring:

  #  mysql数据源
  datasource:
    url: jdbc:p6spy:mysql://172.20.0.2:3306/levelSchool
    username: root
    password: root

  #  redis
  redis:
    database: 0
    host: 172.20.0.1
    port: 6379


server:
  port: 8000
  servlet:
    context-path: /